Algoritmo "semnome"
// 
//  
// Descrição   : solicite o valor do raio e calcule o valor da area da circunferencia
// Autor(a)    : Willliam
// Data atual  : 29/03/2022
Var
// Seção de Declarações das variáveis 
 area, raio:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite o valor do raio")
leia (raio)
area<-pi*raio*raio

escreval("O calculo da área é igual á:",area)


Fimalgoritmo